# Generated by Django 5.2.14 on 2026-05-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_reviewlike_saveditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
