# Generated by Django 5.2.14 on 2026-05-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creator_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='external_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='item',
            name='external_source',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='release_year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
