# Generated by Django 5.2.14 on 2026-05-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_collection_activity_comment_notification_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('review_posted', 'Posted review'), ('review_liked', 'Liked review'), ('user_followed', 'Followed user'), ('recommended', 'Recommended'), ('commented', 'Commented'), ('collection_created', 'Created collection')], max_length=32),
        ),
    ]
