# Generated by Django 5.2.14 on 2026-05-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='profiles/covers/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='profiles/photos/'),
        ),
    ]
