# Generated by Django 5.2.14 on 2026-05-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_profile_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('book', 'Book'), ('series', 'Series'), ('podcast', 'Podcast'), ('experience', 'Experience')], max_length=20),
        ),
    ]
